spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # 수정된 부분
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
      prefix: 'Refresh:'
    excluded:
      path-list:
        /api/members,
        /api/members/login,
        /api/members/refresh_token
jwt:
  prefix: 'Bearer '
  access-token-header: Authorization
  refresh-token-header: Authorization-Refresh
  secret: ${SECRET_KEY}
  access-token-TTL: 300
  refresh-token-TTL: 259200

cookie:
  refresh-token:
    cookie-name: Refresh
    limit-time: 259200
    accepted-url: '/api/members/refresh_token'
    domain: localhost
    http-only: true